/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poly.frame;

import java.util.ArrayList;
import java.util.List;
import poly.frame.HoaDonFrame;
import poly.frame.MainJFrame;
import poly.frame.NhanVienFrame;
import poly.frame.NhatKiNhapSachJFrame;
import poly.frame.TacGiaFrame;
import poly.frame.sach;
import poly.frame.DangNhap;
import poly.model.DanhMucMain;
import poly.model.Main_ManHinhController;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import poly.helper.ShareHelper;


/**
 *
 * @author Admin
 */
public class TrangChuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrangChuJPanel
     */
    
     
    
    public TrangChuJPanel() {
        initComponents();
        
        Main_ManHinhController controller = new Main_ManHinhController(jpnView2);
        
        
        List<DanhMucMain> listItem = new ArrayList<>();
        listItem.add(new DanhMucMain("Main_Sach", jpnSach, jlbIconSach));
        listItem.add(new DanhMucMain("Main_NhanVien", jpnNhanVien, jlbIconNhanVien));
        listItem.add(new DanhMucMain("ThongKe", jpnThongKe, jlbThongKe));
        listItem.add(new DanhMucMain("NhatKi", jpnNhatKi, jlbNhatKi));
        listItem.add(new DanhMucMain("TacGia", jpnTacGia, jlbTacGia));
        listItem.add(new DanhMucMain("HoaDon", jpnHoaDon, jlbHoaDon));

        controller.setEvent(listItem);
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnView2 = new javax.swing.JPanel();
        jpnSach = new javax.swing.JPanel();
        jlbIconSach = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jlbSach = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpnNhanVien = new javax.swing.JPanel();
        jlbIconNhanVien = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jlbNhanVien = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jpnNhatKi = new javax.swing.JPanel();
        jlbIconNhatKi = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jlbNhatKi = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jpnTacGia = new javax.swing.JPanel();
        jlbIconTacGia = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jlbTacGia = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jpnHoaDon = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jlbHoaDon = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jlbIconHoaDon = new javax.swing.JLabel();
        jpnThongKe = new javax.swing.JPanel();
        jlbIconThongKe = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jlbThongKe = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jpnView2.setBackground(new java.awt.Color(51, 0, 102));
        jpnView2.setPreferredSize(new java.awt.Dimension(886, 777));

        jpnSach.setBackground(new java.awt.Color(255, 102, 51));
        jpnSach.setPreferredSize(new java.awt.Dimension(272, 126));
        jpnSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnSachMouseClicked(evt);
            }
        });

        jlbIconSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/images/m_sach_white_36dp.png"))); // NOI18N
        jlbIconSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbIconSachMouseClicked(evt);
            }
        });

        jPanel5.setPreferredSize(new java.awt.Dimension(4, 100));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jlbSach.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbSach.setForeground(new java.awt.Color(255, 255, 255));
        jlbSach.setText("Sách");
        jlbSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbSachMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("15");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnSachLayout = new javax.swing.GroupLayout(jpnSach);
        jpnSach.setLayout(jpnSachLayout);
        jpnSachLayout.setHorizontalGroup(
            jpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSachLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbIconSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnSachLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addContainerGap())
                    .addGroup(jpnSachLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlbSach)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpnSachLayout.setVerticalGroup(
            jpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnSachLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(49, 49, 49)
                        .addComponent(jlbSach)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnSachLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbIconSach)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnNhanVien.setBackground(new java.awt.Color(0, 153, 255));
        jpnNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnNhanVienMouseClicked(evt);
            }
        });

        jlbIconNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/images/m_peo_white_36dp.png"))); // NOI18N
        jlbIconNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbIconNhanVienMouseClicked(evt);
            }
        });

        jPanel7.setPreferredSize(new java.awt.Dimension(4, 100));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jlbNhanVien.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jlbNhanVien.setText("Nhân viên");
        jlbNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbNhanVienMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("5");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnNhanVienLayout = new javax.swing.GroupLayout(jpnNhanVien);
        jpnNhanVien.setLayout(jpnNhanVienLayout);
        jpnNhanVienLayout.setHorizontalGroup(
            jpnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNhanVienLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbIconNhanVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnNhanVienLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addContainerGap())
                    .addGroup(jpnNhanVienLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlbNhanVien)
                        .addContainerGap(60, Short.MAX_VALUE))))
        );
        jpnNhanVienLayout.setVerticalGroup(
            jpnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jpnNhanVienLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbNhanVien))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnNhanVienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbIconNhanVien)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnNhatKi.setBackground(new java.awt.Color(204, 153, 0));
        jpnNhatKi.setPreferredSize(new java.awt.Dimension(272, 126));
        jpnNhatKi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnNhatKiMouseClicked(evt);
            }
        });

        jlbIconNhatKi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/images/m_nhatki_white_36dp.png"))); // NOI18N
        jlbIconNhatKi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbIconNhatKiMouseClicked(evt);
            }
        });

        jPanel9.setPreferredSize(new java.awt.Dimension(4, 100));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jlbNhatKi.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbNhatKi.setForeground(new java.awt.Color(255, 255, 255));
        jlbNhatKi.setText("Nhật kí");
        jlbNhatKi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbNhatKiMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("15");

        javax.swing.GroupLayout jpnNhatKiLayout = new javax.swing.GroupLayout(jpnNhatKi);
        jpnNhatKi.setLayout(jpnNhatKiLayout);
        jpnNhatKiLayout.setHorizontalGroup(
            jpnNhatKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNhatKiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbIconNhatKi)
                .addGap(12, 12, 12)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpnNhatKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnNhatKiLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addContainerGap())
                    .addGroup(jpnNhatKiLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlbNhatKi)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpnNhatKiLayout.setVerticalGroup(
            jpnNhatKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNhatKiLayout.createSequentialGroup()
                .addGroup(jpnNhatKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnNhatKiLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jlbIconNhatKi))
                    .addGroup(jpnNhatKiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnNhatKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbNhatKi)
                            .addGroup(jpnNhatKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jpnTacGia.setBackground(new java.awt.Color(51, 204, 0));
        jpnTacGia.setPreferredSize(new java.awt.Dimension(272, 126));
        jpnTacGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnTacGiaMouseClicked(evt);
            }
        });

        jlbIconTacGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/images/m_tac_white_36dp.png"))); // NOI18N
        jlbIconTacGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbIconTacGiaMouseClicked(evt);
            }
        });

        jPanel11.setPreferredSize(new java.awt.Dimension(4, 100));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jlbTacGia.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbTacGia.setForeground(new java.awt.Color(255, 255, 255));
        jlbTacGia.setText("Tác giả");
        jlbTacGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbTacGiaMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("10");

        javax.swing.GroupLayout jpnTacGiaLayout = new javax.swing.GroupLayout(jpnTacGia);
        jpnTacGia.setLayout(jpnTacGiaLayout);
        jpnTacGiaLayout.setHorizontalGroup(
            jpnTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTacGiaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbIconTacGia)
                .addGap(12, 12, 12)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpnTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnTacGiaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addContainerGap())
                    .addGroup(jpnTacGiaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlbTacGia)
                        .addContainerGap(84, Short.MAX_VALUE))))
        );
        jpnTacGiaLayout.setVerticalGroup(
            jpnTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTacGiaLayout.createSequentialGroup()
                .addGroup(jpnTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnTacGiaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jlbIconTacGia))
                    .addGroup(jpnTacGiaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbTacGia)
                            .addGroup(jpnTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jpnHoaDon.setBackground(new java.awt.Color(255, 102, 102));
        jpnHoaDon.setPreferredSize(new java.awt.Dimension(272, 126));
        jpnHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnHoaDonMouseClicked(evt);
            }
        });

        jPanel12.setPreferredSize(new java.awt.Dimension(4, 100));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jlbHoaDon.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jlbHoaDon.setText("Hóa đơn");
        jlbHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbHoaDonMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("10");

        jlbIconHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/images/main_bill_white_36dp.png"))); // NOI18N
        jlbIconHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbIconHoaDonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnHoaDonLayout = new javax.swing.GroupLayout(jpnHoaDon);
        jpnHoaDon.setLayout(jpnHoaDonLayout);
        jpnHoaDonLayout.setHorizontalGroup(
            jpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHoaDonLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbIconHoaDon)
                .addGap(12, 12, 12)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnHoaDonLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addContainerGap())
                    .addGroup(jpnHoaDonLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbHoaDon)
                        .addContainerGap(78, Short.MAX_VALUE))))
        );
        jpnHoaDonLayout.setVerticalGroup(
            jpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHoaDonLayout.createSequentialGroup()
                .addGroup(jpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnHoaDonLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbHoaDon)
                            .addGroup(jpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpnHoaDonLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jlbIconHoaDon)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jpnThongKe.setBackground(new java.awt.Color(0, 153, 204));
        jpnThongKe.setPreferredSize(new java.awt.Dimension(272, 126));
        jpnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnThongKeMouseClicked(evt);
            }
        });

        jlbIconThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/images/main_chart_white_36dp.png"))); // NOI18N
        jlbIconThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbIconThongKeMouseClicked(evt);
            }
        });

        jPanel13.setPreferredSize(new java.awt.Dimension(4, 100));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jlbThongKe.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbThongKe.setForeground(new java.awt.Color(255, 255, 255));
        jlbThongKe.setText("Thống kê");
        jlbThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbThongKeMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("2");

        javax.swing.GroupLayout jpnThongKeLayout = new javax.swing.GroupLayout(jpnThongKe);
        jpnThongKe.setLayout(jpnThongKeLayout);
        jpnThongKeLayout.setHorizontalGroup(
            jpnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongKeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbIconThongKe)
                .addGap(12, 12, 12)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnThongKeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addContainerGap())
                    .addGroup(jpnThongKeLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlbThongKe)
                        .addContainerGap(69, Short.MAX_VALUE))))
        );
        jpnThongKeLayout.setVerticalGroup(
            jpnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongKeLayout.createSequentialGroup()
                .addGroup(jpnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnThongKeLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jlbIconThongKe))
                    .addGroup(jpnThongKeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbThongKe)
                            .addGroup(jpnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 0, 204));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/images/a_logout.png"))); // NOI18N
        btnLogout.setText("Đăng xuất");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnView2Layout = new javax.swing.GroupLayout(jpnView2);
        jpnView2.setLayout(jpnView2Layout);
        jpnView2Layout.setHorizontalGroup(
            jpnView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnView2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jpnView2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jpnView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnNhatKi, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(jpnView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jpnSach, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(jpnView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jpnView2Layout.setVerticalGroup(
            jpnView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnView2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpnView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jpnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpnSach, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addComponent(jpnTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jpnView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnNhatKi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 416, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnView2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnView2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jpnSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnSachMouseClicked
        // TODO add your handling code here:
        new sach().setVisible(true);
    }//GEN-LAST:event_jpnSachMouseClicked

    private void jlbSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbSachMouseClicked
        // TODO add your handling code here:
        new sach().setVisible(true);
    }//GEN-LAST:event_jlbSachMouseClicked

    private void jlbIconSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbIconSachMouseClicked
        // TODO add your handling code here:
        new sach().setVisible(true);
    }//GEN-LAST:event_jlbIconSachMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new sach().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jpnNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnNhanVienMouseClicked
        new NhanVienFrame().setVisible(true);
    }//GEN-LAST:event_jpnNhanVienMouseClicked

    private void jlbIconNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbIconNhanVienMouseClicked
        // TODO add your handling code here:
        new NhanVienFrame().setVisible(true);
       
    }//GEN-LAST:event_jlbIconNhanVienMouseClicked

    private void jlbNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhanVienMouseClicked
        // TODO add your handling code here:
        new NhanVienFrame().setVisible(true);
    }//GEN-LAST:event_jlbNhanVienMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       new NhanVienFrame().setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jlbHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHoaDonMouseClicked
        // TODO add your handling code here:
        new HoaDonFrame().setVisible(true);
    }//GEN-LAST:event_jlbHoaDonMouseClicked

    private void jlbIconHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbIconHoaDonMouseClicked
        // TODO add your handling code here:
        new HoaDonFrame().setVisible(true);
    }//GEN-LAST:event_jlbIconHoaDonMouseClicked

    private void jpnHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHoaDonMouseClicked
        // TODO add your handling code here:
        new HoaDonFrame().setVisible(true);
    }//GEN-LAST:event_jpnHoaDonMouseClicked

    private void jpnNhatKiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnNhatKiMouseClicked
        // TODO add your handling code here:
        new NhatKiNhapSachJFrame().setVisible(true);
    }//GEN-LAST:event_jpnNhatKiMouseClicked

    private void jlbIconNhatKiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbIconNhatKiMouseClicked
        // TODO add your handling code here:
        new NhatKiNhapSachJFrame().setVisible(true);
    }//GEN-LAST:event_jlbIconNhatKiMouseClicked

    private void jlbNhatKiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNhatKiMouseClicked
        // TODO add your handling code here:
        new NhatKiNhapSachJFrame().setVisible(true);
    }//GEN-LAST:event_jlbNhatKiMouseClicked

    private void jpnThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnThongKeMouseClicked
       if(ShareHelper.USER.isChucVu()==false){
            new ThongKeFrame().setVisible(false);
            JOptionPane.showMessageDialog(this,"Nhân viên không có quyền với chức năng này!!!");
        }
        else{
           new ThongKeFrame().setVisible(true);
             
        }
    }//GEN-LAST:event_jpnThongKeMouseClicked

    private void jlbIconThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbIconThongKeMouseClicked
        if(ShareHelper.USER.isChucVu()==false){
            new ThongKeFrame().setVisible(false);
            JOptionPane.showMessageDialog(this,"Nhân viên không có quyền với chức năng này!!!");
        }
        else{
           new ThongKeFrame().setVisible(true);
             
        }
    }//GEN-LAST:event_jlbIconThongKeMouseClicked

    private void jlbThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbThongKeMouseClicked
        if(ShareHelper.USER.isChucVu()==false){
            new ThongKeFrame().setVisible(false);
            JOptionPane.showMessageDialog(this,"Nhân viên không có quyền với chức năng này!!!");
        }
        else{
           new ThongKeFrame().setVisible(true);
             
        }
    }//GEN-LAST:event_jlbThongKeMouseClicked

    private void jlbIconTacGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbIconTacGiaMouseClicked
        // TODO add your handling code here:
        new TacGiaFrame().setVisible(true);
    }//GEN-LAST:event_jlbIconTacGiaMouseClicked

    private void jpnTacGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnTacGiaMouseClicked
        // TODO add your handling code here:
        new TacGiaFrame().setVisible(true);
    }//GEN-LAST:event_jpnTacGiaMouseClicked

    private void jlbTacGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTacGiaMouseClicked
        // TODO add your handling code here:
        new TacGiaFrame().setVisible(true);
    }//GEN-LAST:event_jlbTacGiaMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.YES_NO_OPTION;
        if(n == JOptionPane.YES_OPTION){
            
            
            new DangNhap(null, true).setVisible(true);             
        }
//        new DangNhap().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jlbHoaDon;
    private javax.swing.JLabel jlbIconHoaDon;
    private javax.swing.JLabel jlbIconNhanVien;
    private javax.swing.JLabel jlbIconNhatKi;
    private javax.swing.JLabel jlbIconSach;
    private javax.swing.JLabel jlbIconTacGia;
    private javax.swing.JLabel jlbIconThongKe;
    private javax.swing.JLabel jlbNhanVien;
    private javax.swing.JLabel jlbNhatKi;
    private javax.swing.JLabel jlbSach;
    private javax.swing.JLabel jlbTacGia;
    private javax.swing.JLabel jlbThongKe;
    private javax.swing.JPanel jpnHoaDon;
    private javax.swing.JPanel jpnNhanVien;
    private javax.swing.JPanel jpnNhatKi;
    private javax.swing.JPanel jpnSach;
    private javax.swing.JPanel jpnTacGia;
    private javax.swing.JPanel jpnThongKe;
    private javax.swing.JPanel jpnView2;
    // End of variables declaration//GEN-END:variables
}
